<?php
namespace Xin\Thrift\OrderService;
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class Order_addGoodsToCart_args {
  static $isValidate = false;

  static $_TSPEC = array(
    1 => array(
      'var' => 'userId',
      'isRequired' => false,
      'type' => TType::I64,
      ),
    2 => array(
      'var' => 'goodsId',
      'isRequired' => false,
      'type' => TType::I64,
      ),
    3 => array(
      'var' => 'shopId',
      'isRequired' => false,
      'type' => TType::I64,
      ),
    4 => array(
      'var' => 'num',
      'isRequired' => false,
      'type' => TType::I32,
      ),
    5 => array(
      'var' => 'unitFee',
      'isRequired' => false,
      'type' => TType::I32,
      ),
    );

  /**
   * @var int
   */
  public $userId = null;
  /**
   * @var int
   */
  public $goodsId = null;
  /**
   * @var int
   */
  public $shopId = null;
  /**
   * @var int
   */
  public $num = null;
  /**
   * @var int
   */
  public $unitFee = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['userId'])) {
        $this->userId = $vals['userId'];
      }
      if (isset($vals['goodsId'])) {
        $this->goodsId = $vals['goodsId'];
      }
      if (isset($vals['shopId'])) {
        $this->shopId = $vals['shopId'];
      }
      if (isset($vals['num'])) {
        $this->num = $vals['num'];
      }
      if (isset($vals['unitFee'])) {
        $this->unitFee = $vals['unitFee'];
      }
    }
  }

  public function getName() {
    return 'Order_addGoodsToCart_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->userId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->goodsId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->shopId);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->num);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::I32) {
            $xfer += $input->readI32($this->unitFee);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Order_addGoodsToCart_args');
    if ($this->userId !== null) {
      $xfer += $output->writeFieldBegin('userId', TType::I64, 1);
      $xfer += $output->writeI64($this->userId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->goodsId !== null) {
      $xfer += $output->writeFieldBegin('goodsId', TType::I64, 2);
      $xfer += $output->writeI64($this->goodsId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->shopId !== null) {
      $xfer += $output->writeFieldBegin('shopId', TType::I64, 3);
      $xfer += $output->writeI64($this->shopId);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->num !== null) {
      $xfer += $output->writeFieldBegin('num', TType::I32, 4);
      $xfer += $output->writeI32($this->num);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->unitFee !== null) {
      $xfer += $output->writeFieldBegin('unitFee', TType::I32, 5);
      $xfer += $output->writeI32($this->unitFee);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

