<?php
namespace Xin\Thrift\OrderService;
/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class Order_place_args {
  static $isValidate = false;

  static $_TSPEC = array(
    1 => array(
      'var' => 'input',
      'isRequired' => false,
      'type' => TType::STRUCT,
      'class' => '\Xin\Thrift\OrderService\Order\PlaceInput',
      ),
    );

  /**
   * @var \Xin\Thrift\OrderService\Order\PlaceInput
   */
  public $input = null;

  public function __construct($vals=null) {
    if (is_array($vals)) {
      if (isset($vals['input'])) {
        $this->input = $vals['input'];
      }
    }
  }

  public function getName() {
    return 'Order_place_args';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->input = new \Xin\Thrift\OrderService\Order\PlaceInput();
            $xfer += $this->input->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Order_place_args');
    if ($this->input !== null) {
      if (!is_object($this->input)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('input', TType::STRUCT, 1);
      $xfer += $this->input->write($output);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

